# Generated by Django 5.1.2 on 2024-10-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('cumparat', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Produs',
                'verbose_name_plural': 'Produse',
            },
        ),
    ]
